name: ervintsay
favicon: null
layout_spectrum: 1
typography_spectrum: 0.52046
title: ervin tsay
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6c6d71'
    - '#221e1f'
    - '#ce0402'
    - '#520201'
    - '#9da1a2'
  brandStrength: 0.75
  lightness: 0.25
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
