name: ervintsay
favicon: null
layout_spectrum: 0.67207
typography_spectrum: 0.52046
title: ervin tsay
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0f1f3'
    - '#6a110b'
    - '#706762'
    - '#b5aba2'
    - '#080300'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
